/**
 * Loader for the WHO LMS tables generated by scripts/build-who-tables.mjs.
 *
 * Tables are read from disk once, on first use, and kept in memory — they are a
 * few hundred kilobytes in total and are read on nearly every request, so
 * touching the filesystem per lookup would be wasteful.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { interpolateLms } from './lms.js';

const DATA_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'data', 'who');

/**
 * `prose` is the form used mid-sentence. It exists because naively lowercasing
 * `label` turns "BMI-for-age" into "bmi-for-age", and acronyms do not survive
 * that.
 */
export const INDICATORS = {
  wfa: { key: 'wfa', label: 'Weight-for-age', prose: 'weight-for-age', short: 'Weight', unit: 'kg', measurement: 'weightKg' },
  lhfa: { key: 'lhfa', label: 'Length/height-for-age', prose: 'length/height-for-age', short: 'Height', unit: 'cm', measurement: 'heightCm' },
  bfa: { key: 'bfa', label: 'BMI-for-age', prose: 'BMI-for-age', short: 'BMI', unit: 'kg/m²', measurement: 'bmi' },
  hcfa: { key: 'hcfa', label: 'Head circumference-for-age', prose: 'head circumference-for-age', short: 'Head', unit: 'cm', measurement: 'headCircumferenceCm' },
};

/** WHO's own convention for converting between days and months in these tables. */
export const DAYS_PER_MONTH = 30.4375;

const cache = new Map();

function load(indicator, sex) {
  const id = `${indicator}-${sex}`;
  if (cache.has(id)) return cache.get(id);

  const file = path.join(DATA_DIR, `${id}.json`);
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    throw new Error(
      `WHO reference table "${id}" is missing. Run \`npm run who:build --workspace=api\` to download it. (${err.code ?? err.message})`,
    );
  }

  // Pre-convert every row's age to days so lookups never branch on unit.
  const perDay = parsed.ageUnit === 'day' ? 1 : parsed.ageUnit === 'week' ? 7 : DAYS_PER_MONTH;
  const table = {
    ...parsed,
    ageDays: parsed.rows.map((r) => r[0] * perDay),
    lms: parsed.rows.map(([, l, m, s]) => ({ l, m, s })),
  };

  cache.set(id, table);
  return table;
}

export function tableFor(indicator, sex) {
  if (!INDICATORS[indicator]) throw new Error(`unknown indicator "${indicator}"`);
  if (sex !== 'male' && sex !== 'female') throw new Error(`unknown sex "${sex}"`);
  return load(indicator, sex);
}

/**
 * LMS triple for an exact age in days, linearly interpolated between the two
 * bracketing table rows. Returns null outside the table's range rather than
 * extrapolating — a z-score derived from an unsupported age would be a lie.
 */
export function lmsAt(indicator, sex, ageDays) {
  const t = tableFor(indicator, sex);
  const ages = t.ageDays;

  if (ageDays < ages[0] || ageDays > ages[ages.length - 1]) return null;

  // Binary search for the last row at or before ageDays.
  let lo = 0;
  let hi = ages.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (ages[mid] <= ageDays) lo = mid;
    else hi = mid - 1;
  }

  if (lo === ages.length - 1 || ages[lo] === ageDays) return t.lms[lo];

  const span = ages[lo + 1] - ages[lo];
  return interpolateLms(t.lms[lo], t.lms[lo + 1], (ageDays - ages[lo]) / span);
}

export function tableRange(indicator, sex) {
  const t = tableFor(indicator, sex);
  return { minDays: t.ageDays[0], maxDays: t.ageDays[t.ageDays.length - 1], ageUnit: t.ageUnit, source: t.source };
}

/** Metadata for the API's /reference endpoint — no LMS values, just provenance. */
export function describeTables() {
  return Object.values(INDICATORS).map((ind) => ({
    ...ind,
    sexes: ['male', 'female'].map((sex) => {
      const t = tableFor(ind.key, sex);
      return { sex, rows: t.rows.length, ageUnit: t.ageUnit, ageMin: t.ageMin, ageMax: t.ageMax, source: t.source };
    }),
  }));
}
